spring:
  application:
    name: zuul
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
#可以注释一下配置,zuul会从eureka拉取注册信息
zuul:
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**

  retryable: true
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream